### ISSUE TITLE
Multiple accounts on one full node wallet, One receive another's incoming results

### ISSUE THREAD

**Issue by flyingcentus** [mvs-org/metaverse#353]

**Comment by flyingcentus** [comment]
![image](https://user-images.githubusercontent.com/52353028/63237924-9e57e280-c276-11e9-95a9-8c980418c1f1.png)
This should be another account's incoming transaction notice, however when I log into another account I receive the notice of the other account's

**Comment by canguruhh** [comment]
@LaurentSalou i think this issue has been resolved

**Comment by LaurentSalou** [comment]
Unfortunately it's not fixed yet, we need to add an unsubscribe to all the addresses on logout

**Comment by canguruhh** [comment]
Maybe we can disconnect from the websocket on logout
