### ISSUE TITLE
BUG: get block header on height pending failed

### ISSUE THREAD

**Issue by Serpent6877** [mvs-org/metaverse#395]
Versions 0.9.1/ 0.9.1b:
OS: Linux

I run a pool with custom Open Ethereum Pool code. Every couple of days or so my unlocker receives this error from the MVSD:

Unlocking suspended due to last critical error: get block header on height pending failed.

```
bool miner::get_block_header(chain::header& block_header, const std::string& para)
{
    if (para == "pending") {
        block_ptr block = get_block();
        if (block) {
            block_header = block->header;
            return true;
        }
    }
    else if (!para.empty()) {
        blockchain::block_chain_impl& block_chain = node_.chain_impl();
        uint64_t height{0};
        if (para == "latest") {
            if (!block_chain.get_last_height(height)) {
                return false;
            }
        }
        else if (para == "earliest") {
            height = 0;
        }
        else if (para[0] >= '0' && para[0] <= '9') {
            height = std::stoull(para);
        }
        else {
            return false;
        }

        if (block_chain.get_header(block_header, height)) {
            block_header.transaction_count = block_chain.get_transaction_count(height);
            return true;
        }
    }

    return false;
}
```

```
block_ptr block = get_block();
```

This part must be failing somewhere. I thought the recent 0.9.1b "BUGFIX: getblock error from height: 3584831 3585067 3585179 because of parsing json format error caused by NaN raw data to resume user scaning MVS blocks." might have been related. But appears not. Any help appreciated.

**Comment by betachen** [comment]
Hi,
Can you send snapshot of screen when `get block header on height pending failed.`, We need more details.

thx

**Comment by canguruhh** [comment]
I think this problem has been resolved in the latest release

**Comment by Serpent6877** [comment]
Still an issue with this:

`
get block header on height pending failed
`

It can run days, then just gives this error from the daemon.  It's so random I have not been able to find a way to replicate it.
